# Generated by Django 5.1.2 on 2024-10-26 04:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunityImpact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_investment",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_energy_savings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_carbon_savings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("equivalent_cars_removed", models.IntegerField()),
                ("equivalent_trees_planted", models.IntegerField()),
            ],
            options={
                "db_table": "community_impact",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("availability", models.BooleanField(default=True)),
                (
                    "energy_produced",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "carbon_reduced_per_stock",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_carbon_reduced",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "dummy_amount",
                    models.DecimalField(
                        decimal_places=2, default=100000, max_digits=10
                    ),
                ),
                ("share_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Projects",
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "total_investment",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_carbon_saving",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_energy_saving",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Merchants",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="EnvironmentalImpact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_carbon_saved",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("equivalent_cars_removed", models.IntegerField()),
                ("equivalent_trees_planted", models.IntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environmental_impacts",
                        to="user.project",
                    ),
                ),
            ],
            options={
                "db_table": "environmental_impact",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=50)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="user.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shares_purchased", models.IntegerField()),
                (
                    "invested_amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("investment_date", models.DateTimeField(auto_now_add=True)),
                ("availability", models.BooleanField(default=True)),
                (
                    "energy_saving",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "carbon_saving",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to="user.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Investments",
                "db_table": "investment",
            },
        ),
        migrations.CreateModel(
            name="EnergySaving",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_energy_generated",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "user_carbon_saved",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("saving_record_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_savings",
                        to="user.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_savings",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "energy_saving",
            },
        ),
    ]
