# Generated by Django 5.1.2 on 2024-10-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="dummy_amount",
        ),
        migrations.AddField(
            model_name="user",
            name="dummy_amount",
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
    ]
